# Generated by Django 3.2.14 on 2022-07-20 06:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='String, 出版社名', max_length=50, null=True, verbose_name='name')),
                ('update_time', models.DateTimeField(db_column='update_time', default=django.utils.timezone.now, max_length=50, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(db_column='create_time', default=django.utils.timezone.now, max_length=50, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '出版社',
                'verbose_name_plural': '出版社',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='String, 图书名称', max_length=50, null=True, verbose_name='name')),
                ('author', models.CharField(blank=True, help_text='String, 图书作者', max_length=50, null=True, verbose_name='author')),
                ('update_time', models.DateTimeField(db_column='update_time', default=django.utils.timezone.now, max_length=50, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(db_column='create_time', default=django.utils.timezone.now, max_length=50, verbose_name='创建时间')),
                ('factory', models.ForeignKey(blank=True, help_text='Int, 出版社', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='book.bookfactory', verbose_name='出版社')),
            ],
            options={
                'verbose_name': '图书表',
                'verbose_name_plural': '图书表',
            },
        ),
    ]
