name: durgin devops aciton

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          export DEVOPS_IMAGE_VERSION=macroldj/devops:v1.0.1
          make prod
          sleep 30
          wget http://127.0.0.1/user/semail/?title=github%20Action&message=%22ci%20successful%22
          sleep 30
          make down