name: durgin djangoer github aciton

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          docker-compose up --build -d
          sleep 20
          docker-compose down
